// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc4h57qjpCE07ncKOd223SX9JWwQLf5UM',
    appId: '1:977892731360:web:adda0ba53ab10142d32385',
    messagingSenderId: '977892731360',
    projectId: 'identificador-plagas-v2',
    authDomain: 'identificador-plagas-v2.firebaseapp.com',
    storageBucket: 'identificador-plagas-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzVilayynKBzyAEv6dI2PlUa31I2JZ6jI',
    appId: '1:977892731360:android:767bda0569c9e3d2d32385',
    messagingSenderId: '977892731360',
    projectId: 'identificador-plagas-v2',
    storageBucket: 'identificador-plagas-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsgoTA7CA8Zj0_xv527UezQOm3p34OgGc',
    appId: '1:977892731360:ios:c9485c5b13853351d32385',
    messagingSenderId: '977892731360',
    projectId: 'identificador-plagas-v2',
    storageBucket: 'identificador-plagas-v2.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsgoTA7CA8Zj0_xv527UezQOm3p34OgGc',
    appId: '1:977892731360:ios:c9485c5b13853351d32385',
    messagingSenderId: '977892731360',
    projectId: 'identificador-plagas-v2',
    storageBucket: 'identificador-plagas-v2.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc4h57qjpCE07ncKOd223SX9JWwQLf5UM',
    appId: '1:977892731360:web:a8509425055be941d32385',
    messagingSenderId: '977892731360',
    projectId: 'identificador-plagas-v2',
    authDomain: 'identificador-plagas-v2.firebaseapp.com',
    storageBucket: 'identificador-plagas-v2.firebasestorage.app',
  );
}
